### PR TITLE
Do not start empty service worker if disabled

### LINKED ISSUE #78: Breaks livereload even when not enabled
Seems like this breaks livereload even when the plugin is not enabled. When I save a scss file it touches the `sw.js` file which causes a full page reload. It does not matter if its enabled or not. Only thing that helps is removing `ember-cli-workbox` from `package.json`. Anyone else got the same issue? 

```
ENV['ember-cli-workbox'] = {
    enabled: false,
    debug: true,
    autoRegister: false,
    importScriptsTransform: importScripts => {
      return importScripts.map(importScript => {
        return process.env.EMBER_ASSETS_ROOT_PATH + importScript;
      });
    },
  };
```

### PR DESCRIPTION
**Pull request by emilkarl**
When plugin disabled dont start an empty service worker. The service worker touches swDest file and causes live reload to do a full page refresh even if the addon is disabled.

By not starting a service worker fixes this issue.

Fixes #78

### CODE REVIEW

**Comment by adrigzr** [comment]
Hi @emilkarl,

Thanks for fixing the issue. For contributing we use semantic-release in order to bump versions on the package. Could you please reword the commit to do a breaking change? The behaviour is slightly different from before and it is not compatible imo.

The commit could be something like:

```
feat(sw): do not create empty SW when disabled

BREAKING CHANGE: SW is removed when addon is disabled.

fix: #79
```

**Comment by emilkarl** [comment]
> Hi @emilkarl,
> 
> Thanks for fixing the issue. For contributing we use semantic-release in order to bump versions on the package. Could you please reword the commit to do a fix?
> 
> The commit could be something like:
> 
> ```
> fix(sw): do not create empty SW when disabled
> 
> fixes: #79
> ```
> 
> EDIT: change breaking change to fix.

Fixed the commit message and also the tests. Please have a look again @josex2r

**Comment by adrigzr** [comment]
Thanks for the change.

I'm thinking on an edge case here:

1. You have SW enabled.
2. You disable it, but the old SW is still installed and running. This will still cache all files even when you does not expect it. 

I think it is necessary to try to disable all old SW that are running when you disable the addon. This is fixed right now due to an empty SW overriding old one. Could you please add a test to ensure this behaviour does not happen?

**Comment by emilkarl** [comment]
> Thanks for the change.
> 
> I'm thinking on an edge case here:
> 
> 1. You have SW enabled.
> 2. You disable it, but the old SW is still installed and running. This will still cache all files even when you does not expect it.
> 
> I think it is necessary to try to disable all old SW that are running when you disable the addon. This is fixed right now due to an empty SW overriding old one. Could you please add a test to ensure this behaviour does not happen?

Cool. Think I solved that now by always removing the service worker file if i exists? What do you think?

**Comment by adrigzr** [comment]
> > Thanks for the change.
> > I'm thinking on an edge case here:
> > 
> > 1. You have SW enabled.
> > 2. You disable it, but the old SW is still installed and running. This will still cache all files even when you does not expect it.
> > 
> > I think it is necessary to try to disable all old SW that are running when you disable the addon. This is fixed right now due to an empty SW overriding old one. Could you please add a test to ensure this behaviour does not happen?
> 
> Cool. Think I solved that now by always removing the service worker file if i exists? What do you think?

I think you also need to unregister current SW on the page with something like [ServiceWorker.unregister](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister).

**Comment by emilkarl** [comment]
> I think you also need to unregister current SW on the page with something like [ServiceWorker.unregister](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister).

I think this is done now. But Im not that familiar with service workers :D

**Comment by adrigzr** [comment]
Hi @emilkarl,

I rechecked and I think it is already unregistering when it is not enabled, so the deletion of the sw.js should do the trick.

https://github.com/BBVAEngineering/ember-cli-workbox/blob/master/app/instance-initializers/sw.js#L28

Restore it to the last version with the file deletion and is ok.

**Comment by emilkarl** [comment]
> Hi @emilkarl,
> 
> I rechecked and I think it is already unregistering when it is not enabled, so the deletion of the sw.js should do the trick.
> 
> https://github.com/BBVAEngineering/ember-cli-workbox/blob/master/app/instance-initializers/sw.js#L28
> 
> Restore it to the last version with the file deletion and it is ok.
> 
> Thanks you!

Done!

**Comment by adrigzr** [comment]
Perfect, thank you! I will try to merge it.

**Comment by oskarer** [comment]
giphub

**Pull request merged**
